### PR TITLE
Author page removal

### PR DESCRIPTION
**Pull request by perfect10-vst**

### CODE REVIEW

**Review by srishti-nema — CHANGES_REQUESTED** [review]
Can you please remove the respective details from `_config.yml` file as well?

**Comment by perfect10-vst** [comment]
> Can you please remove the respective details from `_config.yml` file as well?

Removed

**Review by srishti-nema — APPROVED** [review]
Approving for now, opened #153 to fix build check issues later. Though, I think the changes won't get deployed without the build checks passing...

**Comment by srishti-nema** [comment]
> Approving for now, opened #153 to fix build check issues later. Though, I think the changes won't get deployed without the build checks passing...

Looks like merging to main deploys the changes since it is a static site... I don't think there is a separate deployment mechanism, just some checks and a test preview enabled via Netlify

**Pull request merged**
