### PR TITLE
added post : parallel lines

### PR DESCRIPTION
**Pull request by reversefourseasons**
### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by reversefourseasons** [comment]
@AvikantSrivastava @kaushikikrityy, please review

**Review by KaushikiKrity — APPROVED** [review]

**Review by KaushikiKrity — APPROVED** [review]

**Comment by kaushikikrityy** [comment]
@AvikantSrivastava this looks good to me! You review once!.

**Comment by KaushikiKrity** [comment]
@AvikantSrivastava  This looks perfect to me. It's deploy preview is also there.

**Review by AvikantSrivastava — APPROVED** [review]
The changes are noted, everything looks perfect, the blog is now showing up in the deployment URL.

Amazing job @reversefourseasons and @kaushikikrityy, Thanks for contributing to [LEO MVIT](https://github.com/leomvit)

**Pull request merged**
